count2_health_user:
    resource: "@Count2HealthUserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@Count2HealthAppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
