<?php

namespace Count2Health\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HealthPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HealthPlanRepository extends EntityRepository
{
}
