<?php

namespace Count2Health\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Count2Health\UserBundle\Entity\User;

/**
 * WeightDiaryEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeightDiaryEntryRepository extends EntityRepository
{
    public function findAllByMonth(\DateTime $month)
    {
        $start = clone $month;
        $start->modify('first day of this month');
        $end = clone $start;
        $end->add(new \DateInterval('P1M'));

$em = $this->getEntityManager();

$query = $this->createQueryBuilder('wl')
    ->where('wl.date >= :start')
    ->andWhere('wl.date < :end')
    ->setParameter('start', $start)
    ->setParameter('end', $end)
    ->orderBy('wl.date', 'DESC')
    ->getQuery();

return $query->getResult();
    }

    public function getNumberOfWeightDiaryEntries(User $user)
    {
        return $this->createQueryBuilder('wl')
            ->select('COUNT(wl.id)')
            ->where('wl.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getSingleScalarResult();
    }

}
