<?php

namespace Count2Health\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonalDetailsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalDetailsRepository extends EntityRepository
{
}
